language: python
python:
  - "3.6"
install:
  - pip install -r requirements-dev.txt
script:
  - bandit -r legos/.
  - flake8 .
  - pytest
deploy:
  provider: pypi
  user: drewpearce
  on:
    tags: true
    distributions: sdist bdist_wheel
    branch: master
    repo: drewpearce/legos.memes
  password:
    secure: cGfDw7Da6Cp2oZE8f9K13fOEg8wdjjVEOLL8d+WSbvyH9tiVReWl+XIp12lq7kxcEyxU50Gtxtd7Xae9Gv9ftVHuISlDIf2JSw2Lht3OTJtEv9/x6H2YdaLecpZIO5moh6D4HLEWj7WJOtWSr9V6UFmw7c4Qak+FxQtgjvj9Xii2zNQqcffFBbjDDNIm+2Jq7qXzw5oLtpdUeyuWaP11oDGL9nUajNB01cjwtK0TlAQy0gOrcQxApEl2XnKB71hMQdWxFUF5xYOAeJg8ykYHkhoa2VGA1xfwtWBSJThIoTrd+Mh63Itp4rUK4XAv4lleBcfo9xacNCP0cGC/OvfFWzaffZ1x0MklQ/NuEatrRt1yqggUUciBZyUbIdWyKUvhbIqdqC4AQU5EVOwqISXa8P4QtjNOJBcFqG+KJQCVaXE1Fex/8MfD14q/ub3s11TmNQA0rln+HIiYHfD677w3RCmHkGNr1V3XR+uCZ1kEUT3+u7Q4UvwOdPRHwpeFjxtNO5LhF5w5/YP5yS0xTc5RtHxxmNLkJ6xvFfBzhwpeibypbFeY9Ux+D8mbLiuYee86pSTv6KYLM6jtxz1ZhRHF7ZEylxY8XEvtoM0xHexb00wMj+53pt24JB5wmEYLXyN+udoOXAKTeicH4vuI8IykRS83/zHeitcsT2AshLw2W3k=
